name: "Repo Visualizer"
description: "A GitHub Action that creates an SVG diagram of your repo"
author: "GitHub OCTO"
inputs:
  output_file:
    description: "A path (relative to the root of your repo) to where you would like the diagram to live. For example: images/diagram.svg. Default: diagram.svg"
    required: false
  github_token:
    description: "We need your GitHub token to update the diagram. Specify it like: with: github_token: ${{ secrets.GITHUB_TOKEN }}"
    required: true
runs:
  using: "node12"
  main: "index.js"
branding:
  color: "purple"
  icon: "target"
